# This file is auto-generated by the bigo release workflow.
# Manual changes will be overwritten.
#
# To update manually:
#   1. Download the release binary
#   2. Compute SHA256: shasum -a 256 bigo-darwin-arm64
#   3. Update the version and sha256 values below

class Bigo < Formula
  desc "Unified Claude + Ollama Agent Orchestrator"
  homepage "https://github.com/yourusername/bigo"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yourusername/bigo/releases/download/v#{version}/bigo-darwin-arm64"
      sha256 "PLACEHOLDER_SHA256_DARWIN_ARM64"
    else
      url "https://github.com/yourusername/bigo/releases/download/v#{version}/bigo-darwin-amd64"
      sha256 "PLACEHOLDER_SHA256_DARWIN_AMD64"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/yourusername/bigo/releases/download/v#{version}/bigo-linux-arm64"
      sha256 "PLACEHOLDER_SHA256_LINUX_ARM64"
    else
      url "https://github.com/yourusername/bigo/releases/download/v#{version}/bigo-linux-amd64"
      sha256 "PLACEHOLDER_SHA256_LINUX_AMD64"
    end
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "bigo-darwin-arm64" => "bigo"
      else
        bin.install "bigo-darwin-amd64" => "bigo"
      end
    else
      if Hardware::CPU.arm?
        bin.install "bigo-linux-arm64" => "bigo"
      else
        bin.install "bigo-linux-amd64" => "bigo"
      end
    end
  end

  test do
    assert_match "BigO", shell_output("#{bin}/bigo --version")
  end
end
